In [1]:
import torch

In [4]:

def add_tensors(x: torch.Tensor, y: torch.Tensor) -> torch.Tensor:
    with torch.device('cuda',1):
        result = torch.add(x,y)
    return result

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [5]:
x1 = torch.tensor([[1.,0.,0.],[0.,1.,0.],[0.,0.,1.]])
x2 = torch.tensor([[0.,1.,1.],[1.,0.,1.],[1.,1.,0.]])

x3 = add_tensors(x1,x2)
print(x3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [6]:
x4 = torch.tensor([[1.5,0.,0.],[0.,1.5,0.],[0.,0.,1.5]])
x5 = torch.tensor([[0.,1.2,1.2],[1.2,0.,1.2],[1.,1.,0.]])

x6 = add_tensors(x4,x5)
print(x6)

tensor([[1.5000, 1.2000, 1.2000],
        [1.2000, 1.5000, 1.2000],
        [1.0000, 1.0000, 1.5000]])
