In [ ]:
# From: https://www.tensorflow.org/tutorials/quickstart/beginner

In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)


2024-08-15 11:57:36.706767: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


TensorFlow version: 2.12.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


11490434/11490434 [==============================] - 0s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])


2024-08-15 11:59:40.305100: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [4]:
predictions = model(x_train[:1]).numpy()
predictions


array([[-0.21521941,  0.09957111, -0.4537576 , -0.6891334 ,  0.03850058,
         0.28893542, -0.73147553,  0.11948422, -0.16619596,  0.11764579]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()


array([[0.08957212, 0.12271131, 0.070563  , 0.05576409, 0.11544152,
        0.14829431, 0.05345221, 0.12517937, 0.09407267, 0.12494945]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [7]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [8]:
model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2947 - accuracy: 0.9138
Epoch 2/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.1424 - accuracy: 0.9574
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1069 - accuracy: 0.9678
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0866 - accuracy: 0.9736
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0751 - accuracy: 0.9767


In [9]:
model.evaluate(x_test,  y_test, verbose=2)


313/313 - 1s - loss: 0.0759 - accuracy: 0.9772 - 664ms/epoch - 2ms/step


[0.075938381254673, 0.9771999716758728]

In [10]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


In [11]:
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.9437905e-06, 3.9604633e-10, 1.7852045e-06, 3.4664947e-04,
        5.2488115e-11, 2.9132744e-07, 1.3168801e-11, 9.9963629e-01,
        3.6267472e-06, 9.3547751e-06],
       [1.3268887e-07, 6.3137227e-04, 9.9920279e-01, 1.6106649e-04,
        1.2121348e-14, 1.6346362e-06, 2.0439550e-07, 7.6969586e-14,
        2.8299230e-06, 1.1909043e-11],
       [1.3280759e-05, 9.9738508e-01, 4.5172111e-04, 4.8422109e-05,
        1.7123013e-04, 1.2855886e-05, 8.0592734e-05, 7.0787268e-04,
        1.1211580e-03, 7.7528139e-06],
       [9.9990416e-01, 1.0072614e-09, 4.8658700e-07, 1.0976001e-07,
        9.1374787e-08, 5.8566320e-06, 5.9437876e-05, 2.3083556e-05,
        9.8272700e-08, 6.5890213e-06],
       [1.7431010e-05, 5.3638991e-09, 4.0649456e-06, 3.1832723e-08,
        9.9853671e-01, 6.1594989e-08, 2.3027999e-06, 2.4057516e-04,
        2.3593830e-07, 1.1986461e-03]], dtype=float32)>